# Use postgres/example user/password credentials
version: "3.1"

services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: paspla
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=all"]
  smtp4dev:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - "8181:80"
      - "25:25"
